### ISSUE TITLE
Duplicate data in modis l1 generation

### ISSUE THREAD

**Issue by smacfarlane** [gina-alaska/sandy-utils#12]
https://github.com/gina-alaska/sandy-utils/blob/2c44eec/bin/terra_and_aqua_l1.rb#L77-L96

I'd like to change this to rename the files to the naming convention that polar2grid expects.  

@spruceboy Is there a reason that we're hard linking the output and then copying both files,  rather than renaming and copying?

**Comment by spruceboy** [comment]
The ln is probably in there because I was lazy.

We have three naming conventions in use - the stock one nasa/seadas uses,
which is also used by the other nasa tools like the modis fire points/mod14
stuff, the gina one, used by all kevin's stuff, and the one SSEC uses.

Would it be acceptable to keep the output of seadas (the *.GEO, *.L1B_HKM,
etc) files and create symbolic links for the other two naming schemes, so
other steps using the data don't have to shuffle names around depending
which toolset is using the data?

- Jay Cable - jay@alaska.edu - (907)474-1856 -
- Geographic Information Network of Alaska -  University of Alaska  -

On Fri, Aug 21, 2015 at 11:13 AM, Scott Macfarlane <notifications@github.com

**Comment by smacfarlane** [comment]
cc @teknofire 

I think the scripts should concern themselves with a single output naming convention,  preferably their default or a "gina" name in the case of polar2grid. 

If other scripts are expecting different names, then the wrappers around them is the appropriate place to do the work.

**Comment by teknofire** [comment]
I thought part of the goal of this was to fix some of the legacy aspects of the processing system.  So stuff that relies on specific naming conventions could be updated to be more consistent with the rest of the system.  Seems like relying on symlinks would limit some of the stuff we could do in the future with object stores and what not.

**Comment by spruceboy** [comment]
Using the polar2grid naming scheme is fine.

- Jay Cable - jay@alaska.edu - (907)474-1856 -
- Geographic Information Network of Alaska -  University of Alaska  -
